//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.19 at 08:08:23 PM CEST 
//


package com.xml_web_service.bookingapplication.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Accomodation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Accomodation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parking" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="wifi" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="breakfast" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="halfBoard" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="fullBoard" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="television" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="kitchen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bathroom" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="numberOfPersons">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;pattern value="[0-9]+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pictures" type="{http://com/xml_web_service/bookingapplication/model}Pictures" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CostPlans" type="{http://com/xml_web_service/bookingapplication/model}CostPlans"/>
 *         &lt;element name="address" type="{http://com/xml_web_service/bookingapplication/model}Address"/>
 *         &lt;element name="agent" type="{http://com/xml_web_service/bookingapplication/model}Agent"/>
 *         &lt;element name="accomodationType" type="{http://com/xml_web_service/bookingapplication/model}AccomodationType"/>
 *         &lt;element name="accomodationCategory" type="{http://com/xml_web_service/bookingapplication/model}AccomodationCategory"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Accomodation", propOrder = {
    "id",
    "name",
    "description",
    "parking",
    "wifi",
    "breakfast",
    "halfBoard",
    "fullBoard",
    "television",
    "kitchen",
    "bathroom",
    "numberOfPersons",
    "pictures",
    "costPlans",
    "address",
    "agent",
    "accomodationType",
    "accomodationCategory"
})
public class Accomodation {

    protected long id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    protected boolean parking;
    protected boolean wifi;
    protected boolean breakfast;
    protected boolean halfBoard;
    protected boolean fullBoard;
    protected boolean television;
    protected boolean kitchen;
    protected boolean bathroom;
    protected int numberOfPersons;
    protected List<Pictures> pictures;
    @XmlElement(name = "CostPlans", required = true)
    protected CostPlans costPlans;
    @XmlElement(required = true)
    protected Address address;
    @XmlElement(required = true)
    protected Agent agent;
    @XmlElement(required = true)
    protected AccomodationType accomodationType;
    @XmlElement(required = true)
    protected AccomodationCategory accomodationCategory;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the parking property.
     * 
     */
    public boolean isParking() {
        return parking;
    }

    /**
     * Sets the value of the parking property.
     * 
     */
    public void setParking(boolean value) {
        this.parking = value;
    }

    /**
     * Gets the value of the wifi property.
     * 
     */
    public boolean isWifi() {
        return wifi;
    }

    /**
     * Sets the value of the wifi property.
     * 
     */
    public void setWifi(boolean value) {
        this.wifi = value;
    }

    /**
     * Gets the value of the breakfast property.
     * 
     */
    public boolean isBreakfast() {
        return breakfast;
    }

    /**
     * Sets the value of the breakfast property.
     * 
     */
    public void setBreakfast(boolean value) {
        this.breakfast = value;
    }

    /**
     * Gets the value of the halfBoard property.
     * 
     */
    public boolean isHalfBoard() {
        return halfBoard;
    }

    /**
     * Sets the value of the halfBoard property.
     * 
     */
    public void setHalfBoard(boolean value) {
        this.halfBoard = value;
    }

    /**
     * Gets the value of the fullBoard property.
     * 
     */
    public boolean isFullBoard() {
        return fullBoard;
    }

    /**
     * Sets the value of the fullBoard property.
     * 
     */
    public void setFullBoard(boolean value) {
        this.fullBoard = value;
    }

    /**
     * Gets the value of the television property.
     * 
     */
    public boolean isTelevision() {
        return television;
    }

    /**
     * Sets the value of the television property.
     * 
     */
    public void setTelevision(boolean value) {
        this.television = value;
    }

    /**
     * Gets the value of the kitchen property.
     * 
     */
    public boolean isKitchen() {
        return kitchen;
    }

    /**
     * Sets the value of the kitchen property.
     * 
     */
    public void setKitchen(boolean value) {
        this.kitchen = value;
    }

    /**
     * Gets the value of the bathroom property.
     * 
     */
    public boolean isBathroom() {
        return bathroom;
    }

    /**
     * Sets the value of the bathroom property.
     * 
     */
    public void setBathroom(boolean value) {
        this.bathroom = value;
    }

    /**
     * Gets the value of the numberOfPersons property.
     * 
     */
    public int getNumberOfPersons() {
        return numberOfPersons;
    }

    /**
     * Sets the value of the numberOfPersons property.
     * 
     */
    public void setNumberOfPersons(int value) {
        this.numberOfPersons = value;
    }

    /**
     * Gets the value of the pictures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pictures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPictures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pictures }
     * 
     * 
     */
    public List<Pictures> getPictures() {
        if (pictures == null) {
            pictures = new ArrayList<Pictures>();
        }
        return this.pictures;
    }

    /**
     * Gets the value of the costPlans property.
     * 
     * @return
     *     possible object is
     *     {@link CostPlans }
     *     
     */
    public CostPlans getCostPlans() {
        return costPlans;
    }

    /**
     * Sets the value of the costPlans property.
     * 
     * @param value
     *     allowed object is
     *     {@link CostPlans }
     *     
     */
    public void setCostPlans(CostPlans value) {
        this.costPlans = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link Agent }
     *     
     */
    public Agent getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agent }
     *     
     */
    public void setAgent(Agent value) {
        this.agent = value;
    }

    /**
     * Gets the value of the accomodationType property.
     * 
     * @return
     *     possible object is
     *     {@link AccomodationType }
     *     
     */
    public AccomodationType getAccomodationType() {
        return accomodationType;
    }

    /**
     * Sets the value of the accomodationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccomodationType }
     *     
     */
    public void setAccomodationType(AccomodationType value) {
        this.accomodationType = value;
    }

    /**
     * Gets the value of the accomodationCategory property.
     * 
     * @return
     *     possible object is
     *     {@link AccomodationCategory }
     *     
     */
    public AccomodationCategory getAccomodationCategory() {
        return accomodationCategory;
    }

    /**
     * Sets the value of the accomodationCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccomodationCategory }
     *     
     */
    public void setAccomodationCategory(AccomodationCategory value) {
        this.accomodationCategory = value;
    }

}
