//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.19 at 08:21:15 PM CEST 
//


package com.xml_web_service.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml_web_service.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml_web_service.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAccCategoryRequest }
     * 
     */
    public GetAccCategoryRequest createGetAccCategoryRequest() {
        return new GetAccCategoryRequest();
    }

    /**
     * Create an instance of {@link GetAccTypeResponse }
     * 
     */
    public GetAccTypeResponse createGetAccTypeResponse() {
        return new GetAccTypeResponse();
    }

    /**
     * Create an instance of {@link AccomodationType }
     * 
     */
    public AccomodationType createAccomodationType() {
        return new AccomodationType();
    }

    /**
     * Create an instance of {@link GetAccTypeRequest }
     * 
     */
    public GetAccTypeRequest createGetAccTypeRequest() {
        return new GetAccTypeRequest();
    }

    /**
     * Create an instance of {@link SendAccRequest }
     * 
     */
    public SendAccRequest createSendAccRequest() {
        return new SendAccRequest();
    }

    /**
     * Create an instance of {@link Accomodation }
     * 
     */
    public Accomodation createAccomodation() {
        return new Accomodation();
    }

    /**
     * Create an instance of {@link GetAccCategoryResponse }
     * 
     */
    public GetAccCategoryResponse createGetAccCategoryResponse() {
        return new GetAccCategoryResponse();
    }

    /**
     * Create an instance of {@link AccomodationCategory }
     * 
     */
    public AccomodationCategory createAccomodationCategory() {
        return new AccomodationCategory();
    }

    /**
     * Create an instance of {@link SendAccResponse }
     * 
     */
    public SendAccResponse createSendAccResponse() {
        return new SendAccResponse();
    }

    /**
     * Create an instance of {@link Pictures }
     * 
     */
    public Pictures createPictures() {
        return new Pictures();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link CostPlans }
     * 
     */
    public CostPlans createCostPlans() {
        return new CostPlans();
    }

}
